#!/bin/bash
clear
echo "Resurrection SSH" | lolcat
echo ""
echo ""
echo -e "\033[05;31mSISTEMAS \033[05;33mOPERACIONAIS\033[0m"
echo ""
echo -e "\033[1;31m• \033[1;33mUBUNTU 18-20 x64\033[0m 🐧"
echo -e "\033[1;31m• \033[1;33mDEBIAN  9-11 x64\033[0m 🐧"
echo ""
echo -e "\033[1;33m[*]\033[1;37m ATUALIZANDO SISTEMA..."
apt-get update -y >/dev/null 2>&1 && apt-get upgrade -y >/dev/null 2>&1
echo -e "\033[1;33m[*]\033[1;37m INSTALANDO PACOTES..."
apt-get install lolcat figlet curl git boxes python3 python3-pip socat -y >/dev/null 2>&1
echo -e "\033[1;33m[*]\033[1;37m CONFIGURANDO PYTHON..."
update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.6 1 >/dev/null 2>&1
update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 2 >/dev/null 2>&1
update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 3 >/dev/null 2>&1
update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.9 4 >/dev/null 2>&1
update-alternatives --set python3 /usr/bin/python3.6
echo -e "\033[1;33m[*]\033[1;37m LIMPANDO PACOTES..."
apt-get autoclean -y >/dev/null 2>&1 && apt-get autoremove -y >/dev/null 2>&1
echo -e "\033[1;33m[*]\033[1;37m SCRIPT CONCLUÍDO!"
